```{r}
library(ggplot2)
library(GGally)
library(corrplot)
```

```{r}
load("Kaggle/small_axa.RData")

dim(axa) #600 Observations, 88 Variables
names(axa)
sapply(axa, class)
table(sapply(axa, class)) #Characters need to be converted to numeric type.

sum(is.na(axa)) #3,375 missing values.
na.list = as.data.frame(sapply(axa, function(x) { sum(is.na(x)) })) #Focused in certain variables.
na.list$variable = rownames(na.list)
colnames(na.list) = c("sum.na","variable")
rownames(na.list) <- NULL
na.list[order(na.list$sum.na, decreasing = TRUE), ]

###Converting character variables to numeric variables.
converted.columns = sapply(axa[, 2:87], as.numeric)
axa.converted = data.frame(axa[, 1], converted.columns, axa[, 88])
names(axa.converted) = names(axa) 

axa.converted$driver = as.factor(substr(axa.converted$driver_trip, 1, 1))
names <- names(axa.converted)
names <- gsub("-", "_", names)
names(axa.converted) <- names
remove(axa)
axa = axa.converted
remove(axa.converted)
```

### Data Exploration 
```{r}
summary(axa)
```

Creating boxplots split by driver type and response.
```{r}

var_list = names(axa)[1:89]
boxplot_list = list("null")

for (i in 2:88) {
    p = ggplot(data=axa,aes_string(x=var_list[[89]], y=var_list[[i]],
                                   fill= var_list[[88]])) + 
          geom_boxplot() + ggtitle(i)                   
    boxplot_list[[i]] = p
    }
boxplot_list

ggpairs(data=axa[,c(3, 4, 5, 7, 8, 18, 23, 24, 28, 32, 34, 48, 74, 75, 76, 77, 78, 79, 84, 85,88)], color ="isDriver" )
```


Checking the correlation with variable 79 (`r  colnames(axa[79])`) and selecting the max and min correlations. 
```{r}
correlation_axa = cor(axa[,79] , axa[,2:87] , use = "pairwise.complete.obs")
cor_axa_t = t(correlation_axa)
which.min(cor_axa_t)
which.max(cor_axa_t[-78,])

```
The variables with the highest correaltions are: `r which.min(cor_axa_t)` and `r which.min(cor_axa_t)`


